VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.50.4"

  # play backend
  config.vm.network "forwarded_port", guest: 9000, host: 9000

  # live reload
  # config.vm.network :forwarded_port, guest: 35729, host: 35729

  # ansible configuration
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.verbose = "vvv"
  end

  config.vm.provider "virtualbox" do |v|
  	v.memory = 3072
  	v.cpus = 2
  	v.name = "qualit_dev_vm"
  end

  config.vm.synced_folder "../quali-t-app/", "/quali-t-app/"
end