package models;

import org.hibernate.annotations.DiscriminatorOptions;
import org.hibernate.id.SequenceHiLoGenerator;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Created by emre on 06/03/15.
 */
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public abstract class AbstractEntity implements Serializable {

	@SuppressWarnings("UnusedDeclaration") //generated by hibernate
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	private Long id;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

}
